### ISSUE TITLE
Add Section A Hypothetical Code

### ISSUE THREAD

**Issue by ronaldmunodawafa-hyperiondev** [hyperiondev-com/THT#1]
Hi Pierre and Monique,

Would you please add hypothetical student code for the four options?  They shouldn't employ any third-party frameworks or libraries. The code you submit should be stereotypical of a student scenario.

Pierre, you're responsible for the Java and TypeScript options. Monique, the Ruby and Python options. I'd recommend reviewing some of the newer features in the latest releases of these languages and experimenting with them in your code snippets.

You can use the code blocks where the value is "Please fill...". Please ensure that syntax highlighting is turned for prospective reviewers' accessibility.

You can make pull requests once you're done and I'll review them.

Kind regards

**Comment by Pierre-Roodman-TQS** [comment]
Hi Ronald.

At which level do you propose? Perhaps a late level 1 type of task?
Later than that might require multiple files which won't work so great.

**Comment by ronaldmunodawafa-hyperiondev** [comment]
> Hi Ronald.
> 
> At which level do you propose? Perhaps a late level 1 type of task?

Late Level 1 sounds good!

**Comment by ronaldmunodawafa-hyperiondev** [comment]
Please also include a hypothetical task to match the code you submit.
